name: performance_lista_inicio
description: Ponto de partida — desempenho de renderização em lista longa (Aula 19)
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/produtos.json
